Capstone Project
Enoisong/Capstone-Project pull request #1
Opened 2023-03-24 20:52 UTC by Enoisong

### In this project, I:
- Add an index.html file
- Add style.css file
- Add script.js file
- Add a Loom video presenting my project

2023-03-24 21:51 UTC, jerryowusu reviewed
Hi @Enoisong  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that does not have any future features listed in the readme file. Kindly consider adding one or two points under the future features.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-25 01:03 UTC, mwanawabangona requested changes
Hi @Enoisong ,

Good job so far!
![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-25 01:03 UTC, mwanawabangona commented on README.md
> +-   Contact Page
- [ ] `Required`
- [ ] At the"Acknowledgements" section  thats where you give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).
- [ ] please make adjustments 🥂

2023-03-25 01:03 UTC, mwanawabangona commented on README.md
> +
- [ ] `required`
- [ ] please use of GitHub Pages to deploy the web pages.
- [ ] Make sure the project is deployed properly, all pages, links, and images work as expected.

2023-03-25 01:03 UTC, mwanawabangona commented on index.html
>              @ L' Meridian Resort, Abuja, Nigeria.
- [ ] `required`
- [ ] Please make sure that the spacing, colors, and font size are same.
- [ ] please remove the white background on the navbar so it should similar to the original template.
- [ ] please see screenshot below

`your template`
![image](https://user-images.githubusercontent.com/66230306/227668810-b8d765e3-0300-4a9c-9f8b-6017b4b3c730.png)

`original template`
![image](https://user-images.githubusercontent.com/66230306/227669024-e9ea4212-ede7-4754-8688-2461e8e8c2bc.png)

2023-03-25 01:03 UTC, mwanawabangona commented on index.html
> -
- [ ] `required`
- [ ] please make the boxes be the same size like the original template
![image](https://user-images.githubusercontent.com/66230306/227669563-34b2a6b0-bc38-466a-bb91-462fa02bbf42.png)

2023-03-25 16:55 UTC, amon-cofie approved these changes
Hi @Enoisong , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

🚀 Good commit messages
🚀 No linter errors
🚀 Good pull request summary
🚀 Requested changes well implemented

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 17:24 UTC, merged